### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by vr8hub** [lukasbystricky/jane-austen_northanger_abbey#1]
- [ ] I believe in the preface "By the Authoress of Northanger Abbey" should be considered a subtitle. It's in a different size, etc. in the scans, and "Advertisement" is pretty common as a title.
- [ ] As you noted, we don't need to match inconsequential punctuation, etc. between editions, but the transcription handling of verse is just incorrect. Opening quotes are repeated between _paragraphs_, but not between lines. (Which is how the scans handle it.) So, only the first opening and then the closing quote are needed on the chapter 1 blockquotes. Since you're matching the scans, it doesn't need to be an editorial commit.
- [ ] The dash at the front of verse lines is something we've encountered in other productions, and Alex has had us change them to leading ellipses. That would be editorial.
- [ ] The CSS you have for verse should be replaced with the CSS from [section 7.5](https://standardebooks.org/manual/1.6.4/single-page#7.5) of the manual for poetry/verse/song.
- [ ] Are we sure the 3em dash in chapter 5 is standing in for the Miss's name? There is no space between the Miss and the dash, which would seem to indicate it's a normal "interruption" (or in this case trailing off) dash. I know it's a longer dash in the scans, but they often do that for normal end-of-thought dashes.
- [ ] I believe the _T_ in chapter 21 is more of a concept rather than a grapheme, which would mean it should not be italicized. See [SEMOS 8.2.8](https://standardebooks.org/manual/1.6.4/single-page#8.2.8).
- [ ] I had a couple of Rambler occurrences in what I'm working on and so asked what it should be, and Alex said the corpus uses "magazine" for it (rather than journal).
- [ ] Also on that endnote, we capitalize roman numerals. See [SEMOS 8.8.5.1](https://standardebooks.org/manual/1.6.4/single-page#8.8.5.1).
- [ ] In the letters, the salutations should be in the header; see SEMOS [7.7](https://standardebooks.org/manual/1.6.4/single-page#7.7.2.1). This means you'll need CSS on them to align them normally rather than right. They also need CSS to small-cap them, per the scans.
- [ ] The valedictions need appropriate semantics (also in 7.7).
- [ ] The letters are both quoted in the scans, but only the first one is in the transcription. I'm not sure why they did that, but we should be consistent. We can be consistent with the scans and quote them both, or we can be consistent and remove the quotes from both (since neither are read out loud, there's no real reason for the quotes, but books often quote them anyway).
- [ ] In the metadata, David Widger actually has his own NACOAF id. I'm surprised `create-draft` didn't catch that and add it automatically.
